# Generated by Django 5.0.6 on 2024-06-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('actcod', models.AutoField(db_column='ActCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('actnom', models.CharField(db_column='ActNom', max_length=60, verbose_name='Nombre')),
                ('actfecini', models.DateTimeField(blank=True, db_column='ActfecIni', null=True, verbose_name='Fecha de Inicio')),
                ('actfecfin', models.DateTimeField(blank=True, db_column='ActFecFin', null=True, verbose_name='Fecha de Fin')),
                ('acttip', models.CharField(blank=True, db_column='ActTip', max_length=20, null=True, verbose_name='Tipo')),
                ('acthortradia', models.TimeField(blank=True, db_column='ActHorTraDia', null=True, verbose_name='Horas de Trabajo Diarias')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Complejidad',
            fields=[
                ('comcod', models.AutoField(db_column='ComCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('comnom', models.CharField(db_column='ComNom', max_length=60, verbose_name='Nombre')),
                ('comgra', models.IntegerField(db_column='ComGra', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Complejidad',
                'verbose_name_plural': 'Complejidades',
                'db_table': 'complejidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('estclicod', models.AutoField(db_column='EstCliCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('estclinom', models.CharField(db_column='EstCliNom', max_length=60, verbose_name='Nombre')),
                ('estcliestreg', models.CharField(blank=True, db_column='EstCliEstReg', max_length=20, null=True, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Estado de Cliente',
                'verbose_name_plural': 'Estados de Cliente',
                'db_table': 'estado_cliente',
            },
        ),
        migrations.CreateModel(
            name='EstadoRegistro',
            fields=[
                ('estregcod', models.AutoField(db_column='EstRegCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('estregnom', models.CharField(db_column='EstRegNom', max_length=60, verbose_name='Nombre')),
                ('estregestreg', models.CharField(blank=True, db_column='EstRegEstReg', max_length=20, null=True, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Estado de Registro',
                'verbose_name_plural': 'Estados de Registro',
                'db_table': 'estado_registro',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipclicod', models.AutoField(db_column='TipCliCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('tipclinom', models.CharField(db_column='TipCliNom', max_length=60, verbose_name='Nombre')),
                ('tipcliestreg', models.CharField(blank=True, db_column='TipCliEstReg', max_length=20, null=True, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'db_table': 'tipo_cliente',
            },
        ),
        migrations.CreateModel(
            name='ActividadesComplejidad',
            fields=[
                ('actcomcod', models.AutoField(db_column='ActComCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('actcod', models.ForeignKey(db_column='ActCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.actividad', verbose_name='Actividad')),
                ('comcod', models.ForeignKey(db_column='ComCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.complejidad', verbose_name='Complejidad')),
            ],
            options={
                'verbose_name': 'Actividad por Complejidad',
                'verbose_name_plural': 'Actividades por Complejidad',
                'db_table': 'actividades_complejidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('estprocod', models.AutoField(db_column='EstProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('estpronom', models.CharField(db_column='EstProNom', max_length=60, verbose_name='Nombre')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Estado de Proyecto',
                'verbose_name_plural': 'Estados de Proyecto',
                'db_table': 'estado_proyecto',
            },
        ),
        migrations.AddField(
            model_name='complejidad',
            name='estregcod',
            field=models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clidni', models.IntegerField(db_column='CliDni', primary_key=True, serialize=False, verbose_name='DNI')),
                ('clinom', models.CharField(db_column='CliNom', max_length=100, verbose_name='Nombre')),
                ('clifecing', models.DateField(blank=True, db_column='CliFecIng', null=True, verbose_name='Fecha de Ingreso')),
                ('clifecces', models.DateField(blank=True, db_column='CliFecCes', null=True, verbose_name='Fecha de Cese')),
                ('clifecultprocer', models.DateField(blank=True, db_column='CliFecUltProCer', null=True, verbose_name='Fecha Último Proyecto Cerrado')),
                ('cliestcod', models.ForeignKey(db_column='CliEstCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadocliente', verbose_name='Estado de Cliente')),
                ('regestcod', models.ForeignKey(db_column='RegEstCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
                ('clitipcod', models.ForeignKey(db_column='CliTipCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.tipocliente', verbose_name='Tipo de Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='CargosProyecto',
            fields=[
                ('carprocod', models.AutoField(db_column='CarProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('carpronom', models.CharField(db_column='CarProNom', max_length=60, verbose_name='Nombre')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Cargo de Proyecto',
                'verbose_name_plural': 'Cargos de Proyecto',
                'db_table': 'cargos_proyecto',
            },
        ),
        migrations.CreateModel(
            name='CargosPersonal',
            fields=[
                ('carpercod', models.AutoField(db_column='CarPerCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('carpernom', models.CharField(db_column='CarPerNom', max_length=60, verbose_name='Nombre')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Cargo de Personal',
                'verbose_name_plural': 'Cargos de Personal',
                'db_table': 'cargos_personal',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='estregcod',
            field=models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro'),
        ),
        migrations.CreateModel(
            name='EtapasProyecto',
            fields=[
                ('etaprocod', models.AutoField(db_column='EtaProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('etapronom', models.CharField(db_column='EtaProNom', max_length=60, verbose_name='Nombre')),
                ('etaprofecreg', models.DateTimeField(blank=True, db_column='EtaProFecReg', null=True, verbose_name='Fecha de Registro')),
                ('etaprofecini', models.DateTimeField(blank=True, db_column='EtaProFecIni', null=True, verbose_name='Fecha de Inicio')),
                ('etaprofecfin', models.DateTimeField(blank=True, db_column='EtaProFecFin', null=True, verbose_name='Fecha de Fin')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Etapa de Proyecto',
                'verbose_name_plural': 'Etapas de Proyecto',
                'db_table': 'etapas_proyecto',
            },
        ),
        migrations.CreateModel(
            name='EtapaActividad',
            fields=[
                ('etaactcod', models.AutoField(db_column='EtaActCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('actcod', models.ForeignKey(db_column='ActCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.actividad', verbose_name='Actividad')),
                ('etaprocod', models.ForeignKey(db_column='EtaProCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.etapasproyecto', verbose_name='Etapa del Proyecto')),
            ],
            options={
                'verbose_name': 'Etapa de Actividad',
                'verbose_name_plural': 'Etapas de Actividades',
                'db_table': 'etapa_actividad',
            },
        ),
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('inccod', models.AutoField(db_column='IncCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('incfecini', models.DateTimeField(db_column='IncFecIni', verbose_name='Fecha de Inicio')),
                ('incnom', models.CharField(blank=True, db_column='IncNom', max_length=60, null=True, verbose_name='Nombre')),
                ('incfecfin', models.DateTimeField(blank=True, db_column='IncFecFin', null=True, verbose_name='Fecha de Fin')),
                ('incdes', models.CharField(blank=True, db_column='IncDes', max_length=255, null=True, verbose_name='Descripción')),
                ('actcod', models.ForeignKey(db_column='ActCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.actividad', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('percod', models.AutoField(db_column='PerCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('pernom', models.CharField(db_column='PerNom', max_length=60, verbose_name='Nombre')),
                ('percarcoshor', models.DecimalField(blank=True, db_column='PerCarCosHor', decimal_places=2, max_digits=10, null=True, verbose_name='Costo por Hora')),
                ('perfecing', models.DateField(blank=True, db_column='PerFecIng', null=True, verbose_name='Fecha de Ingreso')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaPersonal',
            fields=[
                ('incpercod', models.AutoField(db_column='IncPerCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('inccod', models.ForeignKey(db_column='IncCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.incidencias', verbose_name='Incidencia')),
                ('percod', models.ForeignKey(db_column='PerCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Incidencia por Personal',
                'verbose_name_plural': 'Incidencias por Personal',
                'db_table': 'incidencia_personal',
            },
        ),
        migrations.CreateModel(
            name='PersonalActividad',
            fields=[
                ('peractcod', models.AutoField(db_column='PerActCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('actcod', models.ForeignKey(db_column='ActCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.actividad', verbose_name='Actividad')),
                ('percod', models.ForeignKey(db_column='PerCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Personal por Actividad',
                'verbose_name_plural': 'Personal por Actividades',
                'db_table': 'personal_actividad',
            },
        ),
        migrations.CreateModel(
            name='PersonalCargosPersonal',
            fields=[
                ('percarpercod', models.AutoField(db_column='PerCarPerCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('percoshorcar', models.IntegerField(blank=True, db_column='PerCosHorCar', null=True, verbose_name='Costo por Hora del Cargo')),
                ('carpercod', models.ForeignKey(db_column='CarPerCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.cargospersonal', verbose_name='Cargo')),
                ('percod', models.ForeignKey(db_column='PerCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Personal por Cargo',
                'verbose_name_plural': 'Personal por Cargos',
                'db_table': 'personal_cargos_personal',
            },
        ),
        migrations.CreateModel(
            name='PersonalCargosProyecto',
            fields=[
                ('percarprocod', models.AutoField(db_column='PerCarProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('carprocod', models.ForeignKey(db_column='CarProCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.cargosproyecto', verbose_name='Cargo de Proyecto')),
                ('percod', models.ForeignKey(db_column='PerCod', on_delete=django.db.models.deletion.CASCADE, to='app_software.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Personal por Cargo de Proyecto',
                'verbose_name_plural': 'Personal por Cargos de Proyecto',
                'db_table': 'personal_cargos_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('prosec', models.AutoField(db_column='ProSec', primary_key=True, serialize=False, verbose_name='Código')),
                ('profecprocon', models.DateField(blank=True, db_column='ProFecProCon', null=True, verbose_name='Fecha de Concepción')),
                ('profecpropac', models.DateField(blank=True, db_column='ProFecProPac', null=True, verbose_name='Fecha Pactada')),
                ('profecproini', models.DateField(blank=True, db_column='ProFecProIni', null=True, verbose_name='Fecha de Inicio')),
                ('profecproent', models.DateField(blank=True, db_column='ProFecProEnt', null=True, verbose_name='Fecha de Entrega')),
                ('profecprocie', models.DateField(blank=True, db_column='ProFecProCie', null=True, verbose_name='Fecha de Cierre')),
                ('promonpro', models.DecimalField(blank=True, db_column='ProMonPro', decimal_places=2, max_digits=10, null=True, verbose_name='Monto Proyectado')),
                ('promonprorea', models.DecimalField(blank=True, db_column='ProMonProRea', decimal_places=2, max_digits=10, null=True, verbose_name='Monto Real')),
                ('promonprocos', models.DecimalField(blank=True, db_column='ProMonProCos', decimal_places=2, max_digits=10, null=True, verbose_name='Costo Proyectado')),
                ('promonprocosrea', models.DecimalField(blank=True, db_column='ProMonProCosRea', decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real')),
                ('promonprogas', models.DecimalField(blank=True, db_column='ProMonProGas', decimal_places=2, max_digits=10, null=True, verbose_name='Gastos Proyectados')),
                ('promonprogasrea', models.DecimalField(blank=True, db_column='ProMonProGasRea', decimal_places=2, max_digits=10, null=True, verbose_name='Gastos Reales')),
                ('promonprouti', models.DecimalField(blank=True, db_column='ProMonProUti', decimal_places=2, max_digits=10, null=True, verbose_name='Utilidad Proyectada')),
                ('promonproutirea', models.DecimalField(blank=True, db_column='ProMonProUtiRea', decimal_places=2, max_digits=10, null=True, verbose_name='Utilidad Real')),
                ('clicod', models.ForeignKey(db_column='CliCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.cliente', verbose_name='Cliente')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
                ('proestprocod', models.ForeignKey(db_column='ProEstProCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoproyecto', verbose_name='Estado del Proyecto')),
                ('proetaprocod', models.ForeignKey(db_column='ProEtaProCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.etapasproyecto', verbose_name='Etapa del Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
            },
        ),
        migrations.AddField(
            model_name='cargosproyecto',
            name='prosec',
            field=models.ForeignKey(db_column='ProSec', on_delete=django.db.models.deletion.CASCADE, to='app_software.proyecto', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('tipprocod', models.AutoField(db_column='TipProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('tippronom', models.CharField(db_column='TipProNom', max_length=60, verbose_name='Nombre')),
                ('estregcod', models.ForeignKey(db_column='EstRegCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Proyecto',
                'verbose_name_plural': 'Tipos de Proyecto',
                'db_table': 'tipo_proyecto',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='protipprocod',
            field=models.ForeignKey(db_column='ProTipProCod', on_delete=django.db.models.deletion.PROTECT, to='app_software.tipoproyecto', verbose_name='Tipo de Proyecto'),
        ),
    ]
