# Generated by Django 5.0.6 on 2024-07-08 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocliente',
            name='estcliestreg',
        ),
        migrations.RemoveField(
            model_name='tipocliente',
            name='tipcliestreg',
        ),
        migrations.AddField(
            model_name='estadocliente',
            name='estregcod',
            field=models.ForeignKey(db_column='EstRegCod', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipocliente',
            name='estregcod',
            field=models.ForeignKey(db_column='EstRegCod', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_software.estadoregistro', verbose_name='Estado de Registro'),
            preserve_default=False,
        ),
    ]
