# Generated by Django 5.0.6 on 2024-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0002_remove_estadocliente_estcliestreg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoregistro',
            name='default',
            field=models.BooleanField(db_column='EstRegIna', default=False, verbose_name='Inactivo'),
        ),
        migrations.AddField(
            model_name='estadoregistro',
            name='is_active',
            field=models.BooleanField(db_column='EstRegAct', default=True, verbose_name='Activo'),
        ),
    ]
