# Generated by Django 5.0.6 on 2024-07-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0003_estadoregistro_default_estadoregistro_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoregistro',
            name='default',
        ),
        migrations.RemoveField(
            model_name='estadoregistro',
            name='is_active',
        ),
    ]
