# Generated by Django 5.0.6 on 2024-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software', '0004_remove_estadoregistro_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='percod',
            field=models.CharField(db_column='DNI', max_length=8, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
    ]
